name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Rename repository
      run: |
        cd ..
        git clone --recursive https://github.com/MattClarkson/CMakeCatchTemplate.git
        CMakeTemplateRenamer/rename.sh CMakeCatchTemplate WorkflowProject WorkflowProject workflowproject WORKFLOWPROJECT "Tom's project" wfp Y pywfp
